export const CATEGORY_NAMES: readonly string[] = [
  'Aerial Platforms',
  'Attachments',
  'Backhoe Loaders',
  'Compactors',
  'Compressors',
  'Cranes',
  'Crushers',
  'Dozers',
  'Excavators',
  'Generators',
  'Lifting Equipment',
  'Wheel Loaders',
  'Motor Graders',
  'Other Equipment',
  'Skid Steers',
  'Trailers',
  'Trucks',
  'Vehicles & Buses',
  'Asphalt Pavers',
  'Unknown',
  'Combination Rollers',
  'Boom Loaders',
  'Pipe Layers',
  'Horizental Drilling Rigs',
  'Container Stackers',
  'Milling Machines',
  'Concrete Pumps',
  'Drilling Machines & Rigs',
  'Concrete Batching Plants',
  'Engines',
  'Spare Parts',
];

// Use the full list for pre-generation to match provided categories
export const PRIORITY_CATEGORY_NAMES: readonly string[] = CATEGORY_NAMES;
